### ISSUE TITLE
Text positioned incorrectly on GUI after 3.6.0 update

### ISSUE THREAD

**Issue by ivan-mogilko** [dkrey/ags_tumbleweed#14]
It seems that the fonts used in this template were prepared for the old AGS behavior, where it would shift letters down a little.

After 3.6.0 update all fonts got their property "TTF font adjustment" set to "Do nothing", but the fonts themselves remain same. This caused the GUI texts (labels, buttons) slightly offset by 1-2 pixels vertically.

Example:
Template of AGS 3.5.1:
![tumbleweed-351](https://user-images.githubusercontent.com/1833754/158864758-269d0b32-923a-4c3c-80ba-0756ff832664.png)
After updated for 3.6.0:
![tumbleweed-360](https://user-images.githubusercontent.com/1833754/158864853-418ee651-b7d2-48df-b37f-ebd3df2fd6bd.png)

The solution is either:
* set "TTF font adjustment" back to "Resize ascender..." backward compatible option, or
* edit the fonts themselves to not need this setting.

**Comment by ericoporto** [comment]
I can edit the fonts, I will look into it. I did notice it before.

**Comment by ivan-mogilko** [comment]
Oh okay.

I think the good way to test this is to make a dummy gui with text buttons, each button using its own font; and then test in 3.5.1 and 3.6.0 template.

**Comment by ericoporto** [comment]
erh, this font in particular (`xpaider2.ttf`) has something that makes it not possible to edit using ttx font tools - this is the only tool I know where I can reliably modify parameters like these... Is it ok if I just turn back the backward compatible option?

**Comment by ericoporto** [comment]
![image](https://user-images.githubusercontent.com/2244442/159085770-59d35282-1121-47ec-b6ce-72725a5c4cd5.png)

Managed to edit the font with ttx font tools!

**Comment by ericoporto** [comment]
@ivan-mogilko can you check if #15 is fine for you?

**Comment by ivan-mogilko** [comment]
Yes, it looks fine; btw we don't have to aim 1:1 comparison, only text to look good, as the new templates don't have to be "backwards compatible" (unlike engine).

**Comment by ericoporto** [comment]
hey I just saw https://github.com/adventuregamestudio/ags/commit/ed971d2c5d289db6df31e2a2214771bcb162e5ca , do I need to change something in the templates for that?

**Comment by ivan-mogilko** [comment]
> hey I just saw https://github.com/adventuregamestudio/ags/commit/ed971d2c5d289db6df31e2a2214771bcb162e5ca , do I need to change something in the templates for that?

No, on contrary, that improves current looks.

**Comment by ericoporto** [comment]
erh, I just tested and after that change I don't need the PR anymore.

**Comment by ivan-mogilko** [comment]
> hey I just saw https://github.com/adventuregamestudio/ags/commit/ed971d2c5d289db6df31e2a2214771bcb162e5ca , do I need to change something in the templates for that?

Hmm... i could have made a mistake there. At least with condition, it should probably test not for game version, but for the font's fixup.

**Comment by ivan-mogilko** [comment]
Ok, let me check the previous template version, if it looks good maybe no font changes are necessary.

OTOH perhaps, because there has been this alignment hack, testing buttons was not the best way to try these fonts out. Perhaps it would be better to try labels, later.
Though, anyway, like i said, we don't have to have 1:1 equality with the previous template version, so long as text look nice.

**Comment by ericoporto** [comment]
hey, I just noticed something in the image above, the sliders thumb are weird

![image](https://user-images.githubusercontent.com/2244442/159094906-bf239a58-0433-4ae3-bf3e-628107381aae.png)
![image](https://user-images.githubusercontent.com/2244442/159094916-fd48c94b-000b-4c3e-b1ad-cab367b91e26.png)

Maybe something needs to be adjusted in the clipping of those too. 🤔

**Comment by ivan-mogilko** [comment]
Regarding slider, i noticed that too yesterday, apparently it's drawn outside of GUI size. Yes, please open the ticket.

Regarding fonts: after my most recent fix (https://github.com/adventuregamestudio/ags/commit/ed971d2c5d289db6df31e2a2214771bcb162e5ca) the button centering became better with most fonts, except xpaider2. So your changes to xpaider2 formally may be good.
**BUT** template's button graphics are also aligned to the old font. So your fixes to xpaider2 + engine fix = bad alignment again...

There might be other ways to workaround this, but maybe we could leave this as is for now. After all, this is just a template.

**Comment by ivan-mogilko** [comment]
Yes, it looks like after https://github.com/adventuregamestudio/ags/commit/ed971d2c5d289db6df31e2a2214771bcb162e5ca this is not necessary, or at least if done, then you'd also have to fix button graphics, or invent another workaround.

So perhaps better not touch anything for now.
