### ISSUE TITLE
Door issue reported in the forums

### ISSUE THREAD

**Issue by ericoporto** [dkrey/ags_tumbleweed#17]
Hi, someone reported this in the forums: https://www.adventuregamestudio.co.uk/forums/index.php?topic=60251.0

> Hello guys, I was testing a few things, I'm trying to get some kind of door lock when closed like no door handle from one side.
> 
> I think I misunderstood the documentation or there's a bug for Doors:AnyClickSpecial
> 
> When using the function for Door interaction and checked the closevalue=2 and I assumed that status would be re-locked (when closed - after being closed), not Locked Forever.
> If this is the case, then I was wrong, and all is good and working as expected.

I think it's about these lines here: 
https://github.com/dkrey/ags_tumbleweed/blob/411d3e14ef1cd91e434db5f03cbd83e70d3776c5/verbgui.asc#L2259-L2269

I am not familiar the doors part of this template, so I could not understand much of the problem, decided to open this in case it's a bug

**Comment by pnfnp** [comment]
Hey there it's me I created the forum, it's quite simple, the `closevalue` of the door should be `0`
```asc
else if (Doors.GetDoorState(door_id) == 2 ) { 
if (verbsData.unlockDoorSound != null) chan = verbsData.unlockDoorSound.Play(); 
if (!String.IsNullOrEmpty(verbsData.door_strings[eDoorStringUnlock])) player.Say(verbsData.door_strings[eDoorStringUnlock]); 
         Doors.SetDoorState(door_id, 0); 
```

I've changed that and all is working fine, the doors after being closed and re-locked can be unlock again and re-opened.

Thanks @ericoporto for creating the bug.

I can create a pull request and make the change if needed.

**Comment by dkrey** [comment]
Thanks for the bug report and already providing the fix 👍 Just added it
