### ISSUE TITLE
Suggestion | ES Translation

### ISSUE THREAD

**Issue by pnfnp** [dkrey/ags_tumbleweed#18]
https://github.com/dkrey/ags_tumbleweed/blob/411d3e14ef1cd91e434db5f03cbd83e70d3776c5/verbgui.asc#L1383-L1387

Hi there I see that there's 2 words that are quite confusing, I've tested with several people and everyone was confused.

`Restablecer` (for `Restore default values`) and `Volver` (`Unpause game`)

I would suggest to say, `Default` and `Jugar`

`verbsgui.asc`
```asc
    btnOptionsDefault.Text = "Default";
    btnOptionsResume.Text  = "Jugar";
```

**Comment by dkrey** [comment]
Since I'm not a native speaker, I can only assume the current translation tries to mimic the classic scumm games.
Anyway - if your translation is more common (or less strange): let's change it.

**Comment by pnfnp** [comment]
No worries, I can create a pull request if you need me to do it. Thanks.

**Comment by dkrey** [comment]
Just pushed it to master. Thanks :)
