### ISSUE TITLE
Sync Custom Dialog to last version 

### ISSUE THREAD

**Issue by ericoporto** [dkrey/ags_tumbleweed#19]
Hey, I don't remember if a release was made of the latest custom dialog, but I think it's a good idea to upgrade the version here to the version in main there: https://github.com/dkrey/ags_customdialog

**Comment by dkrey** [comment]
Hey eri0o,
thanks for the heads up.
The version in this template is a very feature limited and customized version of the custom dialog module. So the bug you've recently fixed in the CDG Module does not apply here, since the border-decoration feature isn't implemented.
