### ISSUE TITLE
Messing with player's location on RestoreGame

### ISSUE THREAD

**Issue by ivan-mogilko** [dkrey/ags_tumbleweed#23]
I found this randomly browsing the template's code:

https://github.com/dkrey/ags_tumbleweed/blob/359e6e7e12c40ab8a538b101423448f51dd5a3b4/GlobalScript.asc#L50-L52

If a save is restored, the player character gets forcefully moved to a walkable area.

I think this is a potential logical problem, as a game could have been saved during a sequence where character was placed onto a custom non-walkable spot, or was moving outside of the walkable area with eAnywhere argument.

On another hand, teleporting character to a walkable area on enter room event may conflict with user's plan to have it behind the room borders for a cutscene, and ordered ChangeRoom with precise coordinates. So I've got doubts about this fixup's convenience also.

**Comment by dkrey** [comment]
The function call has been removed.
