### ISSUE TITLE
Possible updates for 3.6.1

### ISSUE THREAD

**Issue by ivan-mogilko** [dkrey/ags_tumbleweed#24]
Following is a list of possible changes for 3.6.1 version of the template. But I will leave the decision to the template maintainer(s).

- [x] General Settings > Character behavior > "Scale Character sprite offsets" = True (new default value).
- [x] Replace uses of '[' linebreak character with '\n' wherever used: in scripts, and in gui labels, if present.
- [x] Add `SetRestartPoint();` call in `game_start` if this template is using default restart save slot 999. The engine no longer creates one on start, so this has to be done in script now. This is optional.
- [x] `#ifdef/ifndef` pairs may be replaced with `#ifdef/else`.
- [x] If there's any need to dispose temporary resources (such as dynamic sprites) when leaving a room, there's a new event "After fade-out" which is more suitable for this than classic "room leave", because the latter is called before fading out, and while room may still be visible.
- [x] Update interaction callbacks for Characters, Inventory Items, Hotspots and Regions to 3.6.1 style.

In regards to interaction callbacks, these may be tested in a blank game or by adding more, but overall, using examples from original ticket https://github.com/adventuregamestudio/ags/pull/2061 :

The event functions will have following prototype for Characters, Objects, Hotspots and InventoryItems:
```function cEgo_Interact(Character *c, CursorMode mode)```
```function oMyObject_Interact(Object *o, CursorMode mode)```
```function iBlueCup_Interact(InventoryItem *i, CursorMode mode)```
```function hSomeHotspot_Interact(Hotspot *h, CursorMode mode)```

Hotspots have 2 special events without CursorMode param, these are "Walk onto" and "Mouse over":
```function hHotspot2_MouseMove(Hotspot *h)```

Regions do not have CursorMode parameter, because their event types are different, not related to interaction mode:
```function region0_WalksOnto(Region *r)```

**Comment by ivan-mogilko** [comment]
> These sprite(s) should only be deleted after the game stops, not after a room change. Doesn't AGS delete all remaining sprites automatically, after a game stops?

AGS clears all its memory on exit, but this message has been there forever. My guess is that this message notifies user of persistent sprites in case that was not intentional.

> interaction callbacks 3.6.1 style
> The template doesn't use cursor modes at the moment but custom defined interactions. So currently AnyClick functions are being triggered and the action is being checked inside that function.
Switching over to cursor modes would mean that each verbs needs it's own cursor (if I get this right). Anyway this would the whole verb system a lot more static

I'm not suggesting to change how template works, this is only about the function declarations. Script does not have to use the event function arguments. Like, button functions have "GUIControl *control, MouseButton button" arguments, but some or all of these may be ignored if they are not needed.

If the game does not use standard cursor modes, it may still use object pointer sent into the function. To give an example, the 3.6.1 AnyClick looks like this:
```
function cHologram_AnyClick(Character *c, CursorMode mode)
```

Here Character *c may be used to access the character this "any click" event was called for. Of course this is redundant when this function is called strictly for 1 character, but it may be used when same function is connected to multiple characters.

Any new AnyClick function created within 3.6.1 will look like above.

**Comment by ericoporto** [comment]
> AGS clears all its memory on exit, but this message has been there forever. My guess is that this message notifies user of persistent sprites in case that was not intentional.

If I remember correctly, closing the game with alt+F4 still warns even though there isn't some event/callback the engine runs on close - meaning, it may not be possible to totally get rid of dynamic sprite creating warning logs. The good news is these are only created when the engine is in debug mode.

**Comment by dkrey** [comment]
Alright, thanks for the clarification. I'll continue to ignore warnings.log then 😀 
Everything else has been pushed, but needs to be tested for a bit.

**Comment by ivan-mogilko** [comment]
Uhm, I finally checked the latest commits, and I think you misunderstood the intention of adding those parameters to callbacks:
https://github.com/dkrey/ags_tumbleweed/commit/6188de3b15e112636d2df47a1142f67b6d581cb7

There's no need to replace iCup to "i" or cHologram to "c" in these functions code. These functions are only used for 1 item and 1 character, so it's reasonable to keep the corresponding individual scriptnames there.

The reason to use these arguments would be if you'd use same function for multiple objects.

**Comment by dkrey** [comment]
Sorry for the late reply and thanks for the PR. 
I've just merged it!
