### ISSUE TITLE
[tumbleweed template] You can hover and see text when you shouldn't

### ISSUE THREAD

**Issue by Max833** [dkrey/ags_tumbleweed#27]
Even though `mouse.Visible = false;` and `wait = 400;` is active you can still hover over hotspots or enable the menu at the top right with the tumbleweed template. This shouldn't be the case. Same issue when you look at something and the character says something.

### AGS version:
AGS Editor .NET (Build 3.6.1.27)
v3.6.1, August 2024

### Video:
https://streamable.com/55ato2

**Comment by ericoporto** [comment]
Can you give like a picture or video of the cases? It looks like three different things are going on.

**Comment by Max833** [comment]
Hey ericoporoto! :) 
In this video you can see it:  

https://github.com/user-attachments/assets/8586c0f7-a28d-4dae-a5fa-8d13014b57e9

**Comment by ericoporto** [comment]
Thank you for the video, it's easier to understand from it!

**Comment by dkrey** [comment]
Thanks for the bug report and the video. I'll look into it.

**Comment by Max833** [comment]
@dkrey: Yes, it is working now! Thanks a lot. :)

**Comment by dkrey** [comment]
Great, I've just pushed the fix to the repo
