### ISSUE TITLE
What are pmp files?

### ISSUE THREAD

**Issue by ericoporto** [dkrey/ags_tumbleweed#28]
Hi @dkrey , since AGS 3.6.0, it can now reconstruct the spritefile from sources, but so far AGS template export can't package arbitrary stuff - I am looking to change that so that the image file assets from the template files would uncompress in the game dir and people could edit those files and reimport, but also rely in not checking the spritefile into version control because ags would them rebuild the spritefiles from the files - right now this will work unless there are assets kept from the template since those don't exist.

Looking into what to keep and what is not necessary I found that in this template there are a few *.pmp files. What are those?

**Comment by dkrey** [comment]
Hi @ericoporto !
pmp files are ProMotion project files - like .psd files, just for my favourite pixel painter.

**Comment by ericoporto** [comment]
Thank you!
