### ISSUE TITLE
On a Save gui btnSaveSlot1 has wrong height

### ISSUE THREAD

**Issue by ivan-mogilko** [dkrey/ags_tumbleweed#29]
This seems to be a minor issue, not affecting anything, as it looks like that screenshot buttons are adjusted at runtime (?).

But if it matters, btnSaveSlot1 has height 42, while all the other buttons have height 49.
I only noticed this in the editor. In the game it has a correct height.

**Comment by dkrey** [comment]
Thanks for the heads up! Fixed in the AGS4 branch
