### ISSUE TITLE
Set color options using Game.GetColorFromRGB instead of using direct color numbers

### ISSUE THREAD

**Issue by ivan-mogilko** [dkrey/ags_tumbleweed#30]
I noticed that the default values for text color settings are assigned using direct color numbers. For example:

```
  // colour used in action bar
  Verbs.VerbGuiOptions[eVerbGuiActionLabelColorNormal] = 52959;
  
  // highlighted colour used in action bar
  Verbs.VerbGuiOptions[eVerbGuiActionLabelColorHighlighted] = 24188;

<...>

   CustomDialogGui.DialogGuiOptions[eDialogGui_text_color]        = 23420;
   CustomDialogGui.DialogGuiOptions[eDialogGui_text_color_active] = 24188;
```

I propose to fix this and use Game.GetColorFromRGB instead. On one hand that will be easier for the users to understand.
On another hand, that will stay compatible in case anything changes in how engine defines colors. For example, in AGS 4 I've been preparing a change that stores colors as full 32-bit encoded ARGB, in which case these numbers would mean something completely different.

EDIT:
The RGB values may be found, for example, by inserting this number into the Colour Finder input field, or into any ColorNumber property.

**Comment by dkrey** [comment]
That's a very good suggestion, already pushed it to the AGS4 branch of this template.
