### ISSUE TITLE
Spanish Localization "bad" keyboard assigment

### ISSUE THREAD

**Issue by juanmcasillas** [dkrey/ags_tumbleweed#4]
Hello,

In the Spanish Localization, when you assign the keys (`verbgui.asc:1201`):

```
...
 Verbs.LocalizeActionButton(eLangES,eGA_GiveTo,  145, 146, 'y');
```
Key doesn't follow the "block" it should be **z** instead of **y** (I think)

```
 Verbs.LocalizeActionButton(eLangES,eGA_GiveTo,  145, 146, 'z');
```

Thanks for your work!

Kind Regards,
Juan M. Casillas

**Comment by dkrey** [comment]
Hi there,
you're right. I somehow assumed that the qwertz layout is the way to go in europe.
This will be fixed in the next commit and I also changed the french mapping to azerty.
