### ISSUE TITLE
Spanish Localization "should" swap Pickup and Push verbs

### ISSUE THREAD

**Issue by juanmcasillas** [dkrey/ags_tumbleweed#5]
Hello,

In spanish, Push is "Empujar", and this is a long word. Push is a 50x12 icon, so pity.
I manage the problem "swapping" the buttons in the spanish localization. I swap
Push with Pickup (in spanish, pickup is "coger" a short word) I do it changing
`verbgui.asc` (on line `1199`, just before "yes/no" keys mapping):

I put this:
```
    String tr_lang = GetTranslation ("GUI_LANGUAGE");
    tr_lang = tr_lang.LowerCase ();
   
    if (tr_lang == "es") {
      // change use and push (for string length)
      Verbs.SetActionButton(eGA_PickUp,  verbsData.guiMain.Controls[6].AsButton); //3
      Verbs.SetActionButton(eGA_Push,    verbsData.guiMain.Controls[3].AsButton); //6
      // pickup becomes in the position of PUSH
      // push becomes in the position of PICKUP 
    }
```
I leave alone the rest of the translations. It works as expected, using the 56x12 icon slot
for the long word.

Kind Regards,
Juan M. Casillas

**Comment by dkrey** [comment]
Well it depends on what you want to achieve. I know that SCUMM games tend to sort the "long" words in the middle of the grid. Thimbleweed Park on the other hand doesn't shuffle around the verbs anymore and that's what I wanted to mimic in the default settings of this template.
But as you've already found out, it's not so hard to move the verbs around yourself :)

**Comment by dkrey** [comment]
Since there were no compains leaving it unchanged, I'll close this.
