### ISSUE TITLE
When opening subdialogs, gui stuck scrolled in the last element

### ISSUE THREAD

**Issue by juanmcasillas** [dkrey/ags_tumbleweed#6]
Hello (this is the last issue, I promise you, at least for today  👍 )

When you start a new subdialog (calling a dialog from another one) I get that the subdialog starts scrolled to the last element. I didn't want this. I check the options, but looks good (the first dialog shows ok). So I read a little the code and found that in (`CustomDialogGui.asc:317`) (`getRowCount`) when you calls a submenu, 
`CDG_options.scroll_from` is equal to `CDG_options.scroll_to` so I put the following fix:

(`CustomDialogGui.asc:369`)
```
  if (CDG_options.scroll_from == CDG_options.scroll_to) {
      CDG_options.scroll_from =1;      
  }
```

It works in all the cases. I don't know really why (I'm new to AGS and still learning the framework) but ... it fixes my problem.

Thanks for your work.
Juan M. Casillas.

**Comment by dkrey** [comment]
Unfortunately this issue isn't _that_ easy to fix. First of all, I can't get your fix to work. I think for your fix to work the dialog option starting the new dialog, needs to be the last one. And somehow you need to scroll the last option all to the top.

Anyhow - this solution works, but it adds a little extra effort: reset the scrollstate in each subdialog by hand.

So in each dialog, you have this little starting section @S
In there you need to set the scrollposition back to 1. Unfortunately you can't access the variable directly, therefore you need a little helper function.

This is implementation - I will also add it in the next commit.
(The line numbers will differ a bit in your version)

`CustomDialogGui.ash:96`
```
import void restScrollPosition(static CustomDialogGui);
```

`CustomDialogGui.asc:367`
```
void restScrollPosition(static CustomDialogGui) {
  if (CDG_options.dialog_options_upwards) CDG_options.scroll_from = CDG_options.active_options_count;

  else CDG_options.scroll_from = 1;
}
```

`dDialogFooBar`
```
// Dialog script file
@S  // Dialog startup entry point
  CustomDialogGui.restScrollPosition();
```

**Comment by dkrey** [comment]
I've just published the latest release including this fix
